AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DuplicatedAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/LineLength:
  IgnoredPatterns:
    - '"\d+"'
    - '''\d+'''
    - '%(.+)'
    - '^(\s*)# '

Style/NumericPredicate:
  EnforcedStyle: comparison

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
